import Fuse from 'fuse.js';
import type { IFuseOptions, FuseResult } from 'fuse.js';

// Données indexables depuis vos pages
export const searchData = [
  // Guides
  {
    id: 'guide-logement',
    type: 'guide',
    title: 'Trouver un logement',
    description: 'Résidences CROUS, colocation, appartement privé : toutes les options pour vous loger.',
    content: 'CROUS Garant Caution APL résidence étudiante colocation appartement loyer aide logement',
    url: '/guides/logement',
    category: 'Logement',
  },
  {
    id: 'guide-titre-sejour',
    type: 'guide',
    title: 'Titre de séjour',
    description: 'Les démarches pour obtenir et renouveler votre titre de séjour étudiant.',
    content: 'VLS-TS Préfecture OFII Renouvellement visa étudiant titre séjour démarches administratif',
    url: '/guides/titre-sejour',
    category: 'Administratif',
  },
  {
    id: 'guide-securite-sociale',
    type: 'guide',
    title: 'Sécurité sociale',
    description: 'Inscription à la sécurité sociale et accès aux soins en France.',
    content: 'Ameli Carte Vitale Mutuelle Médecin santé sécurité sociale assurance maladie soins',
    url: '/guides/securite-sociale',
    category: 'Santé',
  },
  {
    id: 'guide-banque',
    type: 'guide',
    title: 'Banque & Finances',
    description: 'Ouvrir un compte bancaire et gérer vos finances en tant qu\'étudiant.',
    content: 'Compte RIB Carte Bourses banque finance argent compte bancaire paiement',
    url: '/guides/banque',
    category: 'Finances',
  },
  {
    id: 'guide-scolarite',
    type: 'guide',
    title: 'Scolarité',
    description: 'Inscription universitaire, équivalences et vie étudiante en France.',
    content: 'Inscription Parcoursup CVEC Diplômes université études faculté cours examen',
    url: '/guides/scolarite',
    category: 'Scolarité',
  },
  {
    id: 'guide-transport',
    type: 'guide',
    title: 'Transport',
    description: 'Se déplacer en France : métro, bus, train et réductions étudiantes.',
    content: 'Navigo TGV Vélo Réductions transport métro bus train RER tramway mobilité',
    url: '/guides/transport',
    category: 'Transport',
  },
  {
    id: 'guide-travail',
    type: 'guide',
    title: 'Travail étudiant',
    description: 'Travailler pendant vos études : droits, limites et conseils.',
    content: '20h semaine Stage Alternance Impôts travail job étudiant emploi salaire',
    url: '/guides/travail',
    category: 'Travail',
  },
  {
    id: 'guide-vie-quotidienne',
    type: 'guide',
    title: 'Vie quotidienne',
    description: 'Téléphonie, courses, loisirs : s\'intégrer dans la vie française.',
    content: 'Forfait Supermarché Associations Culture téléphone vie quotidienne courses loisirs',
    url: '/guides/vie-quotidienne',
    category: 'Vie quotidienne',
  },
  // FAQ
  {
    id: 'faq-validation-visa',
    type: 'faq',
    title: 'Combien de temps ai-je pour valider mon visa VLS-TS ?',
    description: 'Vous avez 3 mois après votre entrée en France pour valider votre visa VLS-TS.',
    content: 'validation visa VLS-TS OFII 3 mois 60 euros titre séjour délai validation en ligne',
    url: '/faq#arrivee',
    category: 'Arrivée',
  },
  {
    id: 'faq-prefecture',
    type: 'faq',
    title: 'Dois-je prendre rendez-vous à la préfecture dès mon arrivée ?',
    description: 'Non, pas immédiatement. Validez d\'abord votre visa VLS-TS en ligne.',
    content: 'préfecture rendez-vous VLS-TS validation renouvellement titre séjour démarches',
    url: '/faq#arrivee',
    category: 'Arrivée',
  },
  {
    id: 'faq-logement-trouver',
    type: 'faq',
    title: 'Comment trouver un logement étudiant en France ?',
    description: 'Résidences CROUS, résidences privées, colocation ou chez un particulier.',
    content: 'logement CROUS résidence colocation appartement étudiant trouver louer',
    url: '/faq#logement',
    category: 'Logement',
  },
  {
    id: 'faq-garant',
    type: 'faq',
    title: 'Ai-je besoin d\'un garant pour louer un appartement ?',
    description: 'Généralement oui. Utilisez Visale si vous n\'avez pas de garant en France.',
    content: 'garant Visale Action Logement caution logement appartement garantie locative',
    url: '/faq#logement',
    category: 'Logement',
  },
  {
    id: 'faq-apl',
    type: 'faq',
    title: 'Qu\'est-ce que l\'APL et comment en bénéficier ?',
    description: 'L\'APL est une aide de la CAF qui réduit votre loyer.',
    content: 'APL CAF aide logement loyer allocation personnalisée demande',
    url: '/faq#logement',
    category: 'Logement',
  },
  {
    id: 'faq-securite-sociale',
    type: 'faq',
    title: 'Comment m\'inscrire à la sécurité sociale française ?',
    description: 'L\'inscription se fait sur ameli.fr avec votre attestation universitaire.',
    content: 'sécurité sociale ameli inscription attestation RIB santé carte vitale',
    url: '/faq#sante',
    category: 'Santé',
  },
  {
    id: 'faq-mutuelle',
    type: 'faq',
    title: 'Ai-je besoin d\'une mutuelle en plus de la sécurité sociale ?',
    description: 'La sécurité sociale rembourse 70%. Une mutuelle peut couvrir le reste.',
    content: 'mutuelle sécurité sociale complémentaire santé remboursement',
    url: '/faq#sante',
    category: 'Santé',
  },
  {
    id: 'faq-medecin',
    type: 'faq',
    title: 'Comment trouver un médecin traitant ?',
    description: 'Cherchez sur Doctolib ou Ameli.fr et déclarez-le comme médecin traitant.',
    content: 'médecin traitant Doctolib Ameli santé consultation déclaration',
    url: '/faq#sante',
    category: 'Santé',
  },
  {
    id: 'faq-compte-bancaire',
    type: 'faq',
    title: 'Comment ouvrir un compte bancaire en France ?',
    description: 'Pièce d\'identité, justificatif de domicile et attestation d\'inscription nécessaires.',
    content: 'compte bancaire banque ouverture RIB carte documents pièce identité',
    url: '/faq#banque',
    category: 'Finances',
  },
  {
    id: 'faq-aides-financieres',
    type: 'faq',
    title: 'Quelles aides financières puis-je obtenir ?',
    description: 'APL, bourses sur critères sociaux, aides d\'urgence du CROUS.',
    content: 'aides financières bourses APL CROUS aide urgence allocation',
    url: '/faq#banque',
    category: 'Finances',
  },
  {
    id: 'faq-travail-etudiant',
    type: 'faq',
    title: 'Ai-je le droit de travailler avec un visa étudiant ?',
    description: 'Oui, jusqu\'à 964 heures par an (environ 20h par semaine).',
    content: 'travail étudiant 964 heures 20h semaine visa autorisation job emploi',
    url: '/faq#travail',
    category: 'Travail',
  },
  {
    id: 'faq-job-etudiant',
    type: 'faq',
    title: 'Comment trouver un job étudiant ?',
    description: 'Indeed, Studentjob, sites CROUS, panneaux d\'affichage université.',
    content: 'job étudiant travail emploi Indeed Studentjob CROUS offres',
    url: '/faq#travail',
    category: 'Travail',
  },
  // Pages
  {
    id: 'page-accueil',
    type: 'page',
    title: 'Accueil - Guide du Bleu',
    description: 'Votre guide complet pour réussir votre arrivée et vos études en France.',
    content: 'guide bleu étudiant international primo-arrivant France études université',
    url: '/',
    category: 'Page',
  },
  {
    id: 'page-guides',
    type: 'page',
    title: 'Tous nos guides',
    description: 'Des guides complets, étape par étape, pour votre vie en France.',
    content: 'guides pratiques démarches France étudiant international aide',
    url: '/guides',
    category: 'Page',
  },
  {
    id: 'page-services',
    type: 'page',
    title: 'Nos services',
    description: 'Guides pratiques, assistant IA et communauté pour vous accompagner.',
    content: 'services guides assistant IA chatbot communauté aide accompagnement gratuit',
    url: '/services',
    category: 'Services',
  },
  {
    id: 'page-about',
    type: 'page',
    title: 'À propos du Guide du Bleu',
    description: 'Créé par Diversité Alternative pour les étudiants internationaux.',
    content: 'à propos mission histoire Diversité Alternative association étudiants internationaux solidarité',
    url: '/a-propos',
    category: 'À propos',
  },
  {
    id: 'page-faq',
    type: 'page',
    title: 'Questions fréquentes',
    description: 'Réponses aux questions les plus posées par les étudiants.',
    content: 'FAQ questions fréquentes réponses aide démarches France étudiant',
    url: '/faq',
    category: 'FAQ',
  },
  {
    id: 'page-contact',
    type: 'page',
    title: 'Contactez-nous',
    description: 'Une question, une suggestion ? Nous sommes là pour vous aider.',
    content: 'contact email message question suggestion aide support Diversité Alternative',
    url: '/contact',
    category: 'Contact',
  },
];

// Configuration Fuse.js
const fuseOptions: IFuseOptions<typeof searchData[0]> = {
  keys: [
    { name: 'title', weight: 0.4 },
    { name: 'description', weight: 0.3 },
    { name: 'content', weight: 0.2 },
    { name: 'category', weight: 0.1 },
  ],
  threshold: 0.3, // 0 = exact match, 1 = match anything
  includeScore: true,
  includeMatches: true,
  minMatchCharLength: 2,
  ignoreLocation: true,
  useExtendedSearch: false,
};

export const searchIndex = new Fuse(searchData, fuseOptions);

export type SearchResultItem = typeof searchData[0];
export type SearchResult = FuseResult<SearchResultItem>;
